apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.certIssuer.privateKeyName }}
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
