{{- $portNumber := int .Values.mongodb.service.ports.mongodb }}
{{- $fullname := include "mongodb.fullname" .Subcharts.mongodb }}
{{- $clusterDomain := .Values.mongodb.clusterDomain }}
{{- $replicaCount := int .Values.mongodb.replicaCount }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $mongoList := list }}
{{- range $e, $i := until $replicaCount }}
    {{- $mongoList = append $mongoList (printf "%s-%d.%s-headless.%s.svc.%s" $fullname $i $fullname $releaseNamespace $clusterDomain) }}
{{- end }}
{{- $database := first .Values.mongodb.auth.databases }}
{{- $user := first .Values.mongodb.auth.usernames }}
{{- $pass := ""}}
{{- $rootPass := "" }}
{{- if .Values.mongodb.auth.existingSecret }}
    {{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.mongodb.auth.existingSecret) }}
    {{- $key := "mongodb-passwords" }}
    {{- $pass = index $secret.data $key | b64dec }}
    {{- $rootKey := "mongodb-root-password" }}
    {{- $rootPass =  index $secret.data $rootKey }}
{{- else }}
    {{ $pass = first .Values.mongodb.auth.passwords }}
    {{ $rootPass = .Values.mongodb.auth.rootPassword | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
    name: "mongo-secret"
type: Opaque
data:
    MONGO_URI: {{ printf "%s://%s:%s@%s:%d/" "mongodb" $user $pass (join "," $mongoList) $portNumber | b64enc }}
    SECRET_KEY: {{ "amciusn387sh2kszoi" | b64enc }}
    root-user: {{ .Values.mongodb.auth.rootUser | b64enc }}
    root-pass: {{ $rootPass }}
